### ISSUE TITLE
Firebase instructions missing

### ISSUE THREAD

**Issue by gabazureus** [j05u3/chats_manager#1]
Hello, first of all thank you for the awesome project.

I am trying to run it locally, but I got stuck in this part:

```You also need to follow the instructions for each of the firebase libraries used here (check the pubspec.yaml file). Some of those are: https://github.com/firebase/flutterfire/blob/master/packages/firebase_ui_auth/doc/providers/oauth.md```

I got "File not found".
Can you help, please?

**Comment by j05u3** [comment]
oh, I see the link is broken, will fix it now
